//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColemanFitnessClub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Packet()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ServicesToPackets = new HashSet<ServicesToPacket>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string DateWeek { get; set; }
        public string Date { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesToPacket> ServicesToPackets { get; set; }
    }
}
